wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.19.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1741541458
    t:
      1:
      - 1
      - 55
      3:
      - 4
      - 13
      - 16
      - 23
      - 42
      - 55
      4: 3.11.6
      5: 0.19.7
      8:
      - 5
      13: linux-x86_64
out_dir:
  desc: null
  value: logs
eval_interval:
  desc: null
  value: 125
log_interval:
  desc: null
  value: 1
eval_iters:
  desc: null
  value: 200
eval_only:
  desc: null
  value: false
always_save_checkpoint:
  desc: null
  value: true
init_from:
  desc: null
  value: scratch
wandb_log:
  desc: null
  value: true
wandb_project:
  desc: null
  value: ngpt2025
wandb_run_name:
  desc: null
  value: gpt2_nanogptkarpathy
gradient_accumulation_steps:
  desc: null
  value: 16
batch_size:
  desc: null
  value: 8
block_size:
  desc: null
  value: 4096
n_layer:
  desc: null
  value: 12
n_head:
  desc: null
  value: 6
n_embd:
  desc: null
  value: 768
dropout:
  desc: null
  value: 0.0
bias:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.003
max_iters:
  desc: null
  value: 10000
weight_decay:
  desc: null
  value: 0.1
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.95
grad_clip:
  desc: null
  value: 1.0
decay_lr:
  desc: null
  value: true
warmup_iters:
  desc: null
  value: 2000
lr_decay_iters:
  desc: null
  value: 10000
min_lr:
  desc: null
  value: 0
backend:
  desc: null
  value: nccl
device:
  desc: null
  value: cuda
dtype:
  desc: null
  value: bfloat16
compile:
  desc: null
  value: true
